{% set name = "ruamel.yaml.clib" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ruamel.yaml.clib-{{ version }}.tar.gz
  sha256: 1f08fd5a2bea9c4180db71678e850b995d2a5f4537be0e94557668cf0f5f9497

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<35]
  ignore_run_exports:
    - python
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
    - ruamel.yaml
  commands:
    - pip check
  imports:
    - _ruamel_yaml

about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/{{ version }}/tree/LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
  description: |
    This package was split of from ruamel.yaml, so that ruamel.yaml can be build as a universal wheel.
    Apart from the C code seldom changing, and taking a long time to compile for all platforms, this allows
    installation of the .so on Linux systems under /usr/lib64/pythonX.Y (without a .pth file or a ruamel
    directory) and the Python code for ruamel.yaml under /usr/lib/pythonX.Y.
  doc_url: https://yaml.readthedocs.io
  doc_source_url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/{{ version }}/tree/_doc/
  dev_url: https://sourceforge.net/projects/ruamel-yaml-clib/

extra:
  recipe-maintainers:
    - ocefpaf
